services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simplezzz-fastapi
    ports:
      - "8000:8000"
    environment:
      TZ: Asia/Shanghai
      DB_PATH: /data/data.db
      IMAGE_CACHE_DIR: /data/image_cache
    volumes:
      - .app_data:/data
    restart: unless-stopped
